<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $books = [
            [
                'id' => '9084986f-456c-449b-ae6e-59ef1f26b129',
                'title' => 'CSS in Depth',
                'author' => 'Keith J. Grant',
                'genre' => 'Web Development',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_zIgYlIxcY.png',
                'cover_color' => '#1e2a4b',
                'description' => 'CSS in Depth by Keith J. Grant is a comprehensive guide for web developers who want to go beyond the basics of CSS and master the intricacies of styling web pages. The book is designed for intermediate to advanced developers who are already familiar with CSS but want to deepen their understanding and leverage its full potential.',
                'total_copies' => 18,
                'available_copies' => 16,
                'video_url' => 'https://ik.imagekit.io/pwd17k26p/books/videos/file_O-O0Z_Vz5.png',
                'summary' => 'CSS in Depth starts by reviewing the basic principles of CSS, then quickly moves on to more advanced concepts. Grant emphasizes the importance of understanding the underlying mechanics of CSS properties like layout, box model, and positioning. Readers learn how to use these tools more effectively, making their code more predictable and easier to debug.'
            ],
            [
                'id' => '350c3bc8-a5cc-45a3-ba16-97b93ed056b0',
                'title' => 'HTML and CSS: Design and Build Websites',
                'author' => 'Jon Duckett',
                'genre' => 'Web Development',
                'rating' => 5,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_1pCoBDI11.png',
                'cover_color' => '#3a2931',
                'description' => 'Whether you’re a complete beginner or someone looking to brush up on HTML and CSS, this book provides a solid foundation and practical skills that can be applied immediately to real-world projects.',
                'total_copies' => 45,
                'available_copies' => 45,
                'video_url' => 'https://ik.imagekit.io/pwd17k26p/books/videos/file_MONyhmpr4V.png',
                'summary' => 'HTML and CSS: Design and Build Websites starts with an introduction to HTML, covering the basic building blocks of a webpage, including elements like headings, paragraphs, links, and images. Duckett carefully explains the structure and syntax of HTML, teaching readers how to write and organize their code.'
            ],
            [
                'id' => 'b514f922-a715-45ec-846e-e51d40e15aa2',
                'title' => 'System Design Interview',
                'author' => 'Alex Xu',
                'genre' => 'System Design',
                'rating' => 5,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_CmVaNeXrQ.png',
                'cover_color' => '#363b63',
                'description' => 'System Design Interview: An Insider\'s Guide by Alex Xu is a must-read for software engineers and professionals preparing for system design interviews. The book provides a detailed overview of the principles and techniques needed to excel in system design interviews, which are often a key part of the hiring process at top tech companies.',
                'total_copies' => 10,
                'available_copies' => 10,
                'video_url' => 'https://ik.imagekit.io/pwd17k26p/books/videos/file_x_vGP6M7Y.png',
                'summary' => 'System Design Interview: An Insider\'s Guide begins by introducing the key concepts of system design, emphasizing the importance of understanding requirements, scalability, and reliability. Xu explains how to approach an open-ended problem by breaking it down into smaller, manageable components, ensuring a structured response.'
            ],
            [
                'id' => 'b4ed06bf-02b2-42c4-8886-b3847af02cca',
                'title' => 'Computer Science Distilled',
                'author' => 'Wladston Ferreira Filho',
                'genre' => 'Computer Science',
                'rating' => 5,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_ZRyGl0A75A.png',
                'cover_color' => '#73d173',
                'description' => 'Computer Science Distilled by Wladston Ferreira Filho is a concise and approachable introduction to the core concepts of computer science. Designed for beginners and those looking to strengthen their problem-solving skills, the book breaks down complex topics into digestible, easy-to-understand pieces.',
                'total_copies' => 89,
                'available_copies' => 87,
                'video_url' => 'https://ik.imagekit.io/pwd17k26p/books/videos/file_W6XGeHaEO.png',
                'summary' => 'Computer Science Distilled begins by explaining the art of problem-solving in computing, emphasizing the importance of breaking down problems into manageable parts. It introduces key computational concepts such as abstraction, algorithms, and complexity analysis, providing a strong foundation for tackling any programming challenge.'
            ],
            [
                'id' => 'dc73abc1-8699-4e0a-91b0-a67e80292b9c',
                'title' => 'The Art of Assembly Language',
                'author' => 'Randall Hyde',
                'genre' => 'Programming',
                'rating' => 3,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_lZrAopUNM.png',
                'cover_color' => '#fff9bf',
                'description' => 'The Art of Assembly Language by Randall Hyde is a comprehensive and engaging introduction to assembly language programming. Known for its clarity and depth, the book provides readers with a solid foundation in low-level programming concepts, which are essential for understanding how computers operate at their core.',
                'total_copies' => 78,
                'available_copies' => 78,
                'video_url' => 'https://ik.imagekit.io/pwd17k26p/books/videos/file_VGtFawJik.png',
                'summary' => 'The Art of Assembly Language introduces readers to the fundamentals of assembly programming, beginning with an overview of computer architecture. It explains how CPUs process instructions and manage data, providing the necessary background to appreciate the power of assembly language.'
            ],
            [
                'id' => '8f45a8ad-e0e1-437e-8987-5bcbaca24bd9',
                'title' => 'Seriously Good Software',
                'author' => 'Marco Faella',
                'genre' => 'Programming',
                'rating' => 5,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_YiFXdp5P_T.png',
                'cover_color' => '#061e20',
                'description' => 'This book is perfect for developers who want to elevate their coding skills beyond functionality, making their work robust and professional. Written in an accessible style, Seriously Good Software bridges the gap between theoretical principles and practical application.',
                'total_copies' => 45,
                'available_copies' => 45,
                'video_url' => 'https://ik.imagekit.io/pwd17k26p/books/videos/file_LhwRi_a9cJ.png',
                'summary' => 'Seriously Good Software starts by exploring the core principles of software development, emphasizing the importance of correctness—software must function as intended under all specified conditions. Faella uses clear examples to show how to identify and fix errors that might compromise the correctness of code.'
            ],
            [
                'id' => '91445e57-01a8-4e1e-bb18-cf04b3a0b7d1',
                'title' => 'Fundamentals of Database Systems',
                'author' => 'Ramez Elmasri and Shamkant B. Navathe',
                'genre' => 'Computer Science',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_9-sl0Jo8y.png',
                'cover_color' => '#ffffff',
                'description' => 'Fundamentals of Database Systems by Ramez Elmasri and Shamkant B. Navathe is a comprehensive textbook that serves as a cornerstone for understanding database systems and their applications. This book is widely used in academia and the industry to teach and learn foundational and advanced database concepts.',
                'total_copies' => 145,
                'available_copies' => 145,
                'video_url' => 'https://ik.imagekit.io/pwd17k26p/books/videos/file_UZULgWXVA.png',
                'summary' => 'Fundamentals of Database Systems begins by introducing the fundamental concepts of database systems, including their purpose, architecture, and role in modern computing. It explains key data modeling techniques, such as the Entity-Relationship (ER) model, which is used to design and visualize database schemas.'
            ],
            [
                'id' => 'c3f2ff59-a3c2-47d2-a793-93457a9dccf7',
                'title' => 'Operating System Concepts',
                'author' => 'Abraham Silberschatz, Peter B. Galvin, and Greg Gagne',
                'genre' => 'Computer Science',
                'rating' => 5,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_W6Bz0KiBC.png',
                'cover_color' => '#0e0e10',
                'description' => 'Operating System Concepts, often referred to as the "Dinosaur Book," is a definitive guide to understanding the inner workings of operating systems. Written by Abraham Silberschatz, Peter B. Galvin, and Greg Gagne, this book is an essential resource for students, educators, and professionals in the field of computer science.',
                'total_copies' => 97,
                'available_copies' => 97,
                'video_url' => 'https://ik.imagekit.io/pwd17k26p/books/videos/file_rkMFYr5J0.png',
                'summary' => 'Operating System Concepts provides an in-depth exploration of operating systems, starting with an introduction to their fundamental role in computing. It describes how operating systems manage hardware resources, such as the CPU, memory, and storage, to ensure efficient and reliable operation.'
            ],
            [
                'id' => 'fe03e013-53b8-4574-9ca8-caec69a9b16c',
                'title' => 'Algorithms',
                'author' => 'Robert Sedgewick and Kevin Wayne',
                'genre' => 'Computer Science',
                'rating' => 5,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_dr-f_LPwA.png',
                'cover_color' => '#bf1e2e',
                'description' => 'Algorithms by Robert Sedgewick and Kevin Wayne is a comprehensive and authoritative guide to understanding algorithms and their role in modern computing. Widely regarded as a foundational text in computer science, the book covers a vast array of algorithms, ranging from sorting and searching to graph processing and string manipulation.',
                'total_copies' => 321,
                'available_copies' => 318,
                'video_url' => 'https://ik.imagekit.io/pwd17k26p/books/videos/file_KSZGUHg5R.png',
                'summary' => 'Algorithms is a thorough exploration of algorithmic principles and their applications. It begins with the basics, introducing elementary algorithms like sorting and searching. These foundational topics are covered in-depth, explaining their importance in handling data efficiently and effectively.'
            ],
            [
                'id' => '585df184-991b-4edf-9902-f8531c3a81d9',
                'title' => 'The Clean Coder',
                'author' => 'Robert C. Martin',
                'genre' => 'Software',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_EE5klEyX0.png',
                'cover_color' => '#060709',
                'description' => 'The Clean Coder by Robert C. Martin is an essential guide for software developers who aspire to reach the highest standards of professionalism. Written by one of the most respected figures in the software engineering community, this book transcends technical skills, focusing on the mindset, ethics, and practices that define a professional programmer.',
                'total_copies' => 35,
                'available_copies' => 35,
                'video_url' => 'https://ik.imagekit.io/pwd17k26p/books/videos/file_50K9AmWND.png',
                'summary' => 'The Clean Coder delves into the principles and practices of professional software development. The book begins by defining what it means to be a professional programmer, emphasizing the importance of taking responsibility for your work and acting with integrity.'
            ],
            [
                'id' => 'cea639ce-ee90-4ef9-9fef-c9562a247e99',
                'title' => 'The Lean Startup',
                'author' => 'Eric Ries',
                'genre' => 'Software',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_XyoNwHCdwe.png',
                'cover_color' => '#1E73BE',
                'description' => 'The Lean Startup by Eric Ries is a guide to building and managing startups in a way that maximizes innovation while minimizing wasted effort. The book introduces the concept of the “Lean Startup” methodology, which focuses on quickly turning ideas into products, testing them with real customers, and learning from their feedback to refine and improve.',
                'total_copies' => 17,
                'available_copies' => 17,
                'video_url' => 'https://ik.imagekit.io/pwd17k26p/books/videos/file_uiRdVQTTm.png',
                'summary' => 'The Lean Startup by Eric Ries is a guide to building and managing startups in a way that maximizes innovation while minimizing wasted effort. This approach helps entrepreneurs create successful businesses by avoiding long periods of untested development.'
            ],
            [
                'id' => '68f7c183-b995-4ba3-a644-30110ebb932e',
                'title' => 'Atomic Habits',
                'author' => 'James Clear',
                'genre' => 'Self Help',
                'rating' => 5,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_HOCexO5Ms.png',
                'cover_color' => '#ffffff',
                'description' => 'Atomic Habits by James Clear is a book about how small changes in daily habits can lead to significant transformations over time. Clear emphasizes that habits are the compound interest of self-improvement—tiny actions repeated consistently will eventually produce remarkable results.',
                'total_copies' => 1200,
                'available_copies' => 1200,
                'video_url' => 'https://ik.imagekit.io/pwd17k26p/books/videos/file_WyfBbHfTp.png',
                'summary' => 'Atomic Habits by James Clear is a book about how small changes in daily habits can lead to significant transformations over time. Clear emphasizes that habits are the compound interest of self-improvement.'
            ],
            [
                'id' => 'b6b9cc5d-95fd-488e-b1df-2a805678b430',
                'title' => 'React in Action',
                'author' => 'Mark Tielens Thomas',
                'genre' => 'Web Development',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_rzjr6TrKF.png',
                'cover_color' => '#302428',
                'description' => 'React in Action by Mark Tielens Thomas is a practical guide to mastering React, a popular JavaScript library for building user interfaces. The book is ideal for developers looking to learn React from the ground up and for those seeking to deepen their understanding of its ecosystem.',
                'total_copies' => 57,
                'available_copies' => 57,
                'video_url' => 'https://ik.imagekit.io/pwd17k26p/books/videos/file_jO3MUj8-s.png',
                'summary' => 'React in Action by Mark Tielens Thomas is a practical guide to mastering React. The book starts by introducing the fundamentals of React, including components, JSX, props, and state management, and then explores more advanced topics.'
            ],
            [
                'id' => '17a58b62-0258-45a5-8b8b-9a21a6d6630c',
                'title' => 'JavaScript: The Good Parts',
                'author' => 'Douglas Crockford',
                'genre' => 'Programming',
                'rating' => 5,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_-xOn0_b32.png',
                'cover_color' => '#00a199',
                'description' => 'JavaScript: The Good Parts by Douglas Crockford is a concise guide to understanding and using the best features of JavaScript while avoiding its pitfalls. This book is designed for developers who want to write clean, efficient, and reliable JavaScript code.',
                'total_copies' => 501,
                'available_copies' => 500,
                'video_url' => 'https://ik.imagekit.io/pwd17k26p/books/videos/file_KOYG_-R2J.png',
                'summary' => 'JavaScript: The Good Parts by Douglas Crockford is a concise guide to understanding and using the best features of JavaScript while avoiding its pitfalls. Crockford identifies "the good parts" of JavaScript, such as its dynamic object-oriented nature and functional programming capabilities.'
            ],
            [
                'id' => 'd125678e-80d7-4ba8-97a6-cc6ee4b980ef',
                'title' => 'Eloquent Javascript',
                'author' => 'Marijn Haverbeke',
                'genre' => 'Programming',
                'rating' => 5,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_acYPV3jV0.png',
                'cover_color' => '#F8D347',
                'description' => 'Eloquent JavaScript by Marijn Haverbeke is a deep dive into JavaScript, designed for developers who want to master the language. The book combines clear explanations, practical examples, and exercises to help readers understand both the basics and advanced features of JavaScript.',
                'total_copies' => 121,
                'available_copies' => 120,
                'video_url' => 'https://ik.imagekit.io/pwd17k26p/books/videos/file_l0umqa2H6.png',
                'summary' => 'Eloquent JavaScript by Marijn Haverbeke is a deep dive into JavaScript. The book begins with an introduction to programming concepts and quickly transitions into JavaScript fundamentals, including variables, functions, and control structures.'
            ],
            [
                'id' => '383a8140-08b8-4c7c-97a7-e1bc68dc1488',
                'title' => 'Fullstack React: The Complete Guide to ReactJS and Friends',
                'author' => 'Accomazzo, Greif, and Murray',
                'genre' => 'Web Development',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_aiko1JtEn.png',
                'cover_color' => '#eac8bf',
                'description' => 'Fullstack React: The Complete Guide to ReactJS and Friends by Accomazzo, Greif, and Murray is a comprehensive resource for developers who want to master React and build full-stack applications.',
                'total_copies' => 11,
                'available_copies' => 11,
                'video_url' => 'https://ik.imagekit.io/pwd17k26p/books/videos/file_0HxM1wQe62.png',
                'summary' => 'Fullstack React is a comprehensive resource for developers who want to master React. The book provides step-by-step tutorials, hands-on projects, and deep insights into React\'s ecosystem, making it an excellent guide for both beginners and experienced developers.'
            ],
            [
                'id' => '0aaa12ea-3793-448d-a846-9ab9921f73d9',
                'title' => 'Healty Psychology',
                'author' => 'Shelley E. Taylor',
                'genre' => 'Applied Psychology',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_yryJFVYWd.png',
                'cover_color' => '#2b2b28',
                'description' => 'Cracking the Coding Interview by Gayle Laakmann McDowell is a comprehensive guide for software engineers preparing for technical interviews. The book is packed with insights, strategies, and over 180 programming questions that simulate real interview scenarios.',
                'total_copies' => 32,
                'available_copies' => 32,
                'video_url' => 'https://ik.imagekit.io/pwd17k26p/books/videos/file_vcXsdjkqw.png',
                'summary' => 'Cracking the Coding Interview by Gayle Laakmann McDowell is a comprehensive guide for software engineers preparing for technical interviews. It provides not just solutions but also detailed explanations to help readers understand the reasoning and improve their problem-solving skills.'
            ],
            [
                'id' => 'b36c768b-10b4-4fec-8091-dcc4c406a99b',
                'title' => 'New Educators',
                'author' => 'Marissa Pullman',
                'genre' => 'Educatione',
                'rating' => 5,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_9sl0Jo8y.png',
                'cover_color' => '#1d2078',
                'description' => 'Designing Data-Intensive Applications by Martin Kleppmann is a comprehensive guide to building scalable, reliable, and maintainable data systems. The book covers a wide range of topics, including data models, storage engines, distributed systems, and data processing.',
                'total_copies' => 50,
                'available_copies' => 50,
                'video_url' => 'https://ik.imagekit.io/pwd17k26p/books/videos/file_UZULgWXVA.png',
                'summary' => 'Designing Data-Intensive Applications provides a deep understanding of the principles and practices needed to build robust data systems. It begins with an overview of data models and storage engines, explaining how different approaches affect performance and scalability.'
            ],
            [
                'id' => '8d32ec54-44f0-4dbe-b0d4-05bb37b8a719',
                'title' => 'Designing Data-Intensive Applications',
                'author' => 'Martin Kleppmann',
                'genre' => 'Computer Science',
                'rating' => 5,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_UZULgWXVA.png',
                'cover_color' => '#ffffff',
                'description' => 'Designing Data-Intensive Applications by Martin Kleppmann is a comprehensive guide to building scalable, reliable, and maintainable data systems. The book covers a wide range of topics, including data models, storage engines, distributed systems, and data processing.',
                'total_copies' => 50,
                'available_copies' => 50,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => 'aa21c9bc-1e8a-4da0-a485-6f29b1aed5f8',
                'title' => 'Sostem Informasi Manajemen',
                'author' => 'Yosefina K.I.D.D. Dhea',
                'genre' => 'Machine Learning',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#f2f2f2',
                'description' => 'Machine Learning for Data Science by David Wilson focuses on the intersection of machine learning and data science. The book provides insights into how to leverage machine learning techniques to extract valuable insights from data.',
                'total_copies' => 25,
                'available_copies' => 25,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => 'aa21c9bc-1e8a-4da0-a485-6f29b1aed5f8',
                'title' => 'Pengantar Sistem Informasi',
                'author' => 'George M. MARAKAS',
                'genre' => 'Machine Learning',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#e7e6f0',
                'description' => 'Machine Learning for Engineers by Emily White is a practical guide that focuses on applying machine learning techniques in engineering contexts. The book covers various algorithms and their applications in engineering problems.',
                'total_copies' => 20,
                'available_copies' => 20,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => 'e03a0990-1d58-42a6-9edf-c20d2a44a473',
                'title' => 'Data Mining',
                'author' => 'Fitri Marisa',
                'genre' => 'Machine Learning',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#2518b5',
                'description' => 'Machine Learning for Business by Frank Green explores how businesses can leverage machine learning to gain a competitive edge. The book provides case studies and practical examples of successful machine learning implementations in various industries.',
                'total_copies' => 15,
                'available_copies' => 15,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => '600477cb-9a81-480f-a260-3b0d90582ff2',
                'title' => 'Analisis Data Penelitian',
                'author' => 'Kurniawan',
                'genre' => 'Machine Learning',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#de4e61',
                'description' => 'Machine Learning for Healthcare by Grace Black focuses on the applications of machine learning in the healthcare industry. The book covers topics such as predictive analytics, patient care optimization, and medical imaging.',
                'total_copies' => 10,
                'available_copies' => 10,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => '3137b582-ef46-4d19-9d8b-ca8a24dce6f7',
                'title' => 'SPSS Pengolahan Data $ Analisis Data',
                'author' => 'Romis Priyatama',
                'genre' => 'Machine Learning',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#f2e6ee',
                'description' => 'Machine Learning for Finance by Henry Gold explores how machine learning can be applied in the financial sector. The book covers algorithmic trading, risk assessment, and fraud detection.',
                'total_copies' => 12,
                'available_copies' => 12,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => 'b1c8f3d2-4a0e-4b5c-9f6d-7c8e1f2a3b4c',
                'title' => 'Pengantar Sistem Basis Data',
                'author' => 'Dr. Rudianto, M.Kom.',
                'genre' => 'Machine Learning',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#f0f0f0',
                'description' => 'Machine Learning for Marketing by Ivy Blue focuses on how machine learning can enhance marketing strategies. The book covers customer segmentation, personalized marketing, and campaign optimization.',
                'total_copies' => 20,
                'available_copies' => 20,
                'video_url' => null,
                'summary' => null
            ],      
            [
                'id' => 'e801c512-641b-4a0d-8454-a81d69717e89',
                'title' => 'Sistem Basis Dta',
                'author' => 'Agnes Novita Ida S.',
                'genre' => 'Machine Learning',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#db8148',
                'description' => 'Machine Learning for Marketing by Ivy Blue focuses on how machine learning can enhance marketing strategies. The book covers customer segmentation, personalized marketing, and campaign optimization.',
                'total_copies' => 18,
                'available_copies' => 18,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => '7c171705-843b-4810-8a64-1c07b962ddfe',
                'title' => 'Aplikasi Teknologi Internet of Things',
                'author' => 'Muhammad Zen Samsono Hadi ',
                'genre' => 'Machine Learning',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#4034eb',
                'description' => 'Machine Learning for Robotics by Jack Silver explores the intersection of machine learning and robotics. The book covers topics such as robot perception, navigation, and control systems.',
                'total_copies' => 22,
                'available_copies' => 22,
                'video_url' => null,
                'summary' => null
           ],
           [
                'id' => '585a0c4e-911a-4469-907a-a3757c85df2b',
                'title' => 'Teknologi BIG DATA',
                'author' => 'W.M Wijaya, B.Eng, M.Eng',
                'genre' => 'Machine Learning',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#242733',
                'description' => 'Machine Learning for IoT by Kate Green focuses on applying machine learning techniques to Internet of Things (IoT) devices. The book covers topics such as sensor data analysis, predictive maintenance, and smart home applications.',
                'total_copies' => 15,
                'available_copies' => 15,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => '849fada7-0e55-4d08-b7ac-0837be95029b',
                'title' => 'Pengantar Teknologi WEB',
                'author' => 'Drs., Afrizal Zein, M.Kom.',
                'genre' => 'Machine Learning',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#464a5c',
                'description' => 'Machine Learning for Cybersecurity by Liam Brown explores how machine learning can enhance cybersecurity measures. The book covers threat detection, anomaly detection, and intrusion prevention.',
                'total_copies' => 10,
                'available_copies' => 10,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => '41ef0f23-c138-48d2-a8dd-dbb96d5ceb78',
                'title' => 'Pemograman Internet Dasar',
                'author' => 'Indah Purnama Sari, S.I., M.Kom.',
                'genre' => 'Machine Learning',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#98acfa',
                'description' => 'Machine Learning for Supply Chain by Mia White focuses on applying machine learning techniques to optimize supply chain operations. The book covers demand forecasting, inventory management, and logistics optimization.',
                'total_copies' => 12,
                'available_copies' => 12,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => '0c2b36b3-b282-414f-8f22-04faa5c80cd9',
                'title' => 'Teknologi Informasi dan Komunikasi',
                'author' => 'Hamdan Husein Batubara, M.Pd.I',
                'genre' => 'Machine Learning',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#f2f3f7',
                'description' => 'Machine Learning for Education by Nina Black explores how machine learning can enhance educational practices. The book covers personalized learning, student performance prediction, and adaptive learning systems.',
                'total_copies' => 8,
                'available_copies' => 8,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => '2d0e6a92-27cd-4900-99dd-3af87470d41a',
                'title' => 'Teknologi Informasi, Komunikasi dan Pendikanan',
                'author' => 'Dr.Shoffan Shaffa, S.Pd, M.Pd',
                'genre' => 'Machine Learning',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#2a3b82',
                'description' => 'Machine Learning for Agriculture by Oscar Green focuses on applying machine learning techniques to agricultural practices. The book covers crop yield prediction, soil analysis, and precision farming.',
                'total_copies' => 10,
                'available_copies' => 10,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => 'cee269eb-edfc-44fe-baa9-eedadb3e51e7',
                'title' => 'Roadmap Broadband IndonesiaEra Teknologi 5G',
                'author' => 'Denny Kusuma Hendraningrat',
                'genre' => 'Machine Learning',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#546bc4',
                'description' => 'Machine Learning for Smart Cities by Paul Blue explores how machine learning can enhance urban living. The book covers smart transportation, energy management, and public safety.',
                'total_copies' => 15,
                'available_copies' => 15,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => 'e8a439ba-cf88-4014-9474-98386c3a0545',
                'title' => 'Teknologi Informasi dan Komunikasi',
                'author' => 'Prof.Dr.Utari Soemarno',
                'genre' => 'Machine Learning',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#2e3140',
                'description' => 'Machine Learning for Environmental Science by Quinn Yellow focuses on applying machine learning techniques to environmental studies. The book covers climate modeling, biodiversity analysis, and pollution monitoring.',
                'total_copies' => 10,
                'available_copies' => 10,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => '8ea3f88d-620a-47bd-9120-415e40c38409',
                'title' => 'Pengantar Teknologi Informasi',
                'author' => 'Prof.Dr.Ir. Edi Neorsasongko, M.Kom.',
                'genre' => 'Machine Learning',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#3049b0',
                'description' => 'Machine Learning for Sports Analytics by Rita Purple explores how machine learning can enhance sports performance analysis. The book covers player performance prediction, game strategy optimization, and fan engagement.',
                'total_copies' => 12,
                'available_copies' => 12,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => '64c46a63-82df-4997-a6ce-4773906d768e',
                'title' => 'Teknologi untuk Masa Depan',
                'author' => 'Najela Shihab',
                'genre' => 'Machine Learning',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#6a82e6',
                'description' => 'Machine Learning for Social Good by Sam Orange explores how machine learning can be applied to address social challenges. The book covers topics such as disaster response, poverty alleviation, and public health.',
                'total_copies' => 15,
                'available_copies' => 15,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => '6d81ebea-52e8-4577-84c9-72adcb519a7a',
                'title' => 'Teknologi Pendidikan',
                'author' => 'Drs. Syamsul Arif, M.Pd',
                'genre' => 'Machine Learning',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#215236',
                'description' => 'Machine Learning for Natural Language Processing by Tina Pink focuses on applying machine learning techniques to natural language processing tasks. The book covers text classification, sentiment analysis, and language generation.',
                'total_copies' => 20,
                'available_copies' => 20,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => '70b4aee2-c09c-40f8-b04f-05a6ee42c234',
                'title' => 'Koleksi Perpustakaan',
                'author' => 'Jarot Ariyanto',
                'genre' => 'Machine Learning',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#2b2727',
                'description' => 'Machine Learning for Image Processing by Uma Gray explores how machine learning can enhance image processing tasks. The book covers image classification, object detection, and image generation.',
                'total_copies' => 18,
                'available_copies' => 18,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => 'c91d3941-f655-456d-943e-4146e403d64e',
                'title' => 'The Story OF Hellen Keller',
                'author' => 'Hellen Keller',
                'genre' => 'biography',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#2b2727',
                'description' => 'Machine Learning for Audio Processing by Vera Silver focuses on applying machine learning techniques to audio processing tasks. The book covers speech recognition, music genre classification, and sound synthesis.',
                'total_copies' => 15,
                'available_copies' => 15,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => '826f091d-71be-4fb8-a8f2-2a32742e7ec4',
                'title' => 'Fisafat Ilmu Etika Akademik',
                'author' => 'Will Gold',
                'genre' => 'law',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#2b2727',
                'description' => 'Machine Learning for Video Analysis by Will Gold explores how machine learning can enhance video analysis tasks. The book covers video classification, action recognition, and video generation.',
                'total_copies' => 12,
                'available_copies' => 12,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => '5d2ac660-30b7-463c-8010-709ed275f002',
                'title' => 'Hukum Perdata Internasional',
                'author' => 'Dr.Ronaldi Saijah, S.H,. M.H',
                'genre' => 'law',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#c21018',
                'description' => 'Machine Learning for Time Series Analysis by Xena Blue focuses on applying machine learning techniques to time series data. The book covers forecasting, anomaly detection, and trend analysis.',
                'total_copies' => 10,
                'available_copies' => 10,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => '9de211af-8de9-404a-b48e-81362cf2f418',
                'title' => 'Hukum Perlindungan Konsumen',
                'author' => 'Dr.Abdul Atsar, S.H,. M.H',
                'genre' => 'law',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#c21018',
                'description' => 'Machine Learning for Graph Data by Yara Green explores how machine learning can be applied to graph data structures. The book covers graph neural networks, link prediction, and community detection.',
                'total_copies' => 8,
                'available_copies' => 8,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => '2e0bbd4e-9c4c-47bb-8cc7-542d2d9429c0',
                'title' => 'Ilmu Kesehatan',
                'author' => 'Dr,dr. Umar Zein',
                'genre' => 'health',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#2c382f',
                'description' => 'Machine Learning for Reinforcement Learning by Zara Red focuses on applying machine learning techniques to reinforcement learning tasks. The book covers policy gradients, Q-learning, and deep reinforcement learning.',
                'total_copies' => 10,
                'available_copies' => 10,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => 'fc6d0794-9889-4ae7-ae3b-cbba077800eb',
                'title' => 'Etika Leperawatan',
                'author' => 'Crishartonto, S.Kep,. Ns',
                'genre' => 'health',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#e4ebe5',
                'description' => 'Machine Learning for Federated Learning by Alex Silver explores how machine learning can be applied in federated learning scenarios. The book covers distributed learning, privacy-preserving techniques, and collaborative models.',
                'total_copies' => 12,
                'available_copies' => 12,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => 'e5542675-55d2-4cf0-b33d-73be5aa6b3b9',
                'title' => 'Keperawatan Kesehatan Komunitas',
                'author' => 'Primawati Kusumawati, S.Kep,. Ns',
                'genre' => 'health',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#098729',
                'description' => 'Machine Learning for Quantum Computing by Bella Gold explores how machine learning can be applied in quantum computing contexts. The book covers quantum algorithms, quantum neural networks, and quantum data analysis.',
                'total_copies' => 10,
                'available_copies' => 10,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => 'c98e861d-8d4d-4aca-ae00-c30b59af5180',
                'title' => 'Iman Sebagai Basis Psikologi Pengembangan Karakter',
                'author' => 'Dr.H.Alivermana Wiguna , M.Ag',
                'genre' => 'religion',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#e9e8ed',
                'description' => 'Machine Learning for Blockchain by Charlie Blue explores how machine learning can enhance blockchain technologies. The book covers smart contracts, decentralized applications, and blockchain analytics.',
                'total_copies' => 15,
                'available_copies' => 15,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => 'd2653a86-5d00-424c-a425-9c9a64ae54ce',
                'title' => 'Mnanajeman Starategi',
                'author' => 'Zuriani Ritonga, S,E,. M.M',
                'genre' => 'business',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#14093b',
                'description' => 'Machine Learning for Edge Computing by Diana Green focuses on applying machine learning techniques in edge computing environments. The book covers edge device optimization, real-time analytics, and distributed learning.',
                'total_copies' => 10,
                'available_copies' => 10,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => '0f5d4491-7c29-4b22-a2d9-954f15c77187',
                'title' => 'digital marketing',
                'author' => 'dr. Usman Chamnadi',
                'genre' => 'education',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#c90a20',
                'description' => 'Machine Learning for Autonomous Systems by Ethan Red explores how machine learning can enhance autonomous systems. The book covers self-driving cars, drones, and robotic systems.',
                'total_copies' => 12,
                'available_copies' => 12,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => '00452cd8-4151-405b-9786-fc59ba701bf9',
                'title' => 'Psikolog Pendidikan',
                'author' => 'Mahsup, S.pd,. M.Pd',
                'genre' => 'mental health',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#9225a8',
                'description' => 'Machine Learning for Smart Manufacturing by Fiona Silver focuses on applying machine learning techniques to manufacturing processes. The book covers predictive maintenance, quality control, and production optimization.',
                'total_copies' => 15,
                'available_copies' => 15,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => '092a4f93-7003-4f1d-89b8-683e41d36f3a',
                'title' => 'Perspektif Pendidikan dalam Bingkai Ilmu dan Tokoh',
                'author' => 'Kurniawan',
                'genre' => 'Education',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => 'v',
                'description' => 'Machine Learning for Smart Energy Systems by George Gold explores how machine learning can optimize energy systems. The book covers smart grids, energy consumption prediction, and renewable energy integration.',
                'total_copies' => 10,
                'available_copies' => 10,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => '63164ba5-4ea1-4666-b3b7-9563c88d4170',
                'title' => 'Pengantar Perbandingan Hukum Waris',
                'author' => 'Dr. Rio Christian, S.H., M.Hum., M.Kn',
                'genre' => 'Self-Help',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#e9eef0',
                'description' => 'Machine Learning for Smart Transportation by Hannah Blue focuses on applying machine learning techniques to transportation systems. The book covers traffic prediction, route optimization, and smart mobility solutions.',
                'total_copies' => 12,
                'available_copies' => 12,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => 'cc233bf8-2a50-4b79-828f-63ff64f41fe0',
                'title' => 'Hukum Perusahaan',
                'author' => 'Ahmad Miru',
                'genre' => 'Self-Help',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#e9eef0',
                'description' => 'Machine Learning for Smart Healthcare by Ian Green explores how machine learning can enhance healthcare systems. The book covers telemedicine, remote patient monitoring, and health data analytics.',
                'total_copies' => 10,
                'available_copies' => 10,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => '95b511b3-c635-4519-92ce-0116aeffa24d',
                'title' => 'Digital Perpustakaan Daerah',
                'author' => 'Prof. Dr. Deitje Katuuk, M.Pd',
                'genre' => 'Self-Help',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#e9eef0',
                'description' => 'Machine Learning for Smart Agriculture by Jack Red focuses on applying machine learning techniques to agricultural practices. The book covers precision farming, crop monitoring, and yield prediction.',
                'total_copies' => 15,
                'available_copies' => 15,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => 'e4f2aa08-17bc-450c-91e7-83fdc84b11c4',
                'title' => 'inovasi perpustakaan diera covid-19',
                'author' => 'Ubudiah setiawati',
                'genre' => 'Self-Help',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#e9eef0',
                'description' => 'Machine Learning for Smart Cities by Liam Silver explores how machine learning can enhance urban living. The book covers smart infrastructure, public safety, and citizen engagement.',
                'total_copies' => 12,
                'available_copies' => 12,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => '0dfd8467-54e9-4aa5-9e4d-18c1443c9bd8',
                'title' => 'Aku yang sudah lama hilang',
                'author' => 'Nego Tejena',
                'genre' => 'Self-Help',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#e9eef0',
                'description' => 'Machine Learning for Smart Finance by Mia Gold focuses on applying machine learning techniques to financial systems. The book covers algorithmic trading, risk management, and fraud detection.',
                'total_copies' => 10,
                'available_copies' => 10,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => '4ee75455-3e71-4af2-bad0-2ad8477d105b',
                'title' => 'Personal Branding',
                'author' => 'Tom Liwafa',
                'genre' => 'Self-Help',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#087e99',
                'description' => 'Machine Learning for Smart Retail by Nina Blue explores how machine learning can enhance retail operations. The book covers customer behavior analysis, inventory management, and personalized marketing.',
                'total_copies' => 15,
                'available_copies' => 15,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => 'd05a7d003-8afe-415c-95e8-410745561424',
                'title' => 'The Humans',
                'author' => 'Matt Haig',
                'genre' => 'Self-Help',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#237d91',
                'description' => 'Machine Learning for Smart Logistics by Oscar Red focuses on applying machine learning techniques to logistics and supply chain management. The book covers route optimization, demand forecasting, and inventory management.',
                'total_copies' => 12,
                'available_copies' => 12,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => '743e68fc-5569-4571-adc3-e82523eaf220',
                'title' => 'Berbohong dengan statistik',
                'author' => 'Darrell Huff',
                'genre' => 'Self-Help',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#ff5252',
                'description' => 'Machine Learning for Smart Telecommunications by Paul Green explores how machine learning can enhance telecommunications systems. The book covers network optimization, customer experience management, and predictive maintenance.',
                'total_copies' => 10,
                'available_copies' => 10,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => '2b5cb899-4bd6-4563-b970-ee3d8fbde7e1',
                'title' => 'Sebuah Seni untuk Bersikap Bodo Amat',
                'author' => 'Mark Manson',
                'genre' => 'Self-Help',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#ff5252',
                'description' => 'Machine Learning for Smart Water Management by Quinn Silver focuses on applying machine learning techniques to water management systems. The book covers water quality monitoring, demand forecasting, and leak detection.',
                'total_copies' => 8,
                'available_copies' => 8,
                'video_url' => null,
                'summary' => null
            ],
            [
                'id' => 'c4c789a4-5e0f-44d4-bfd5-d4e3949036ed',
                'title' => 'Alasan untuk Tetap Hidup',
                'author' => 'Matt Haig',
                'genre' => 'Self-Help',
                'rating' => 4,
                'cover_url' => 'https://ik.imagekit.io/pwd17k26p/books/covers/file_0HxM1wQe62.png',
                'cover_color' => '#4e8ade',
                'description' => 'Machine Learning for Smart Waste Management by Rita Gold explores how machine learning can enhance waste management systems. The book covers waste collection optimization, recycling prediction, and waste reduction strategies.',
                'total_copies' => 10,
                'available_copies' => 10,
                'video_url' => null,
                'summary' => null
            ],
            []


        ];

        DB::table('books')->insert($books);
    }
}
